
FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    apt-get update -y  && \
    apt-get install -y git  && \
    apt-get install -y vim
RUN apt-get update && \
    apt-get install -y curl \
    wget \
    openjdk-11-jdk

RUN apt-get install -y default-jre

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y eclipse-platform

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/jre/bin/java

RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get update
Run apt-get install -y ethereum

RUN apt install -y build-essential

RUN curl -sL https://deb.nodesource.com/setup_6.x
RUN apt-get install -y nodejs
RUN apt-get install -y npm

RUN npm install -g ganache-cli
RUN npm install -g express

RUN npm install -g solc
RUN apt update

RUN mkdir /dapp
WORKDIR "/dapp"
RUN npm install -g truffle@4.1.15
RUN npm install -g --save ethereumjs-testrpc
EXPOSE 8080
CMD ["/bin/bash"]